apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv003
spec:
  claimRef:
    namespace: default
    name: solemn-lambkin-mysql
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
      #  storageClassName: manual
  hostPath:
    path: "/mnt/data"

#  persistentVolumeReclaimPolicy: Recycle
#  storageClassName: slow
#  nfs:
#    path: /tmp
#    server: 172.17.0.2
