#api:
#  dashboard: true
#  insecure: true
#entryPoints:
#  entryPoints.web:
#    address: ":800"
#  entryPoints.websecure:
#    address: ":443"
#ping: {}
#accesslog:
#  filePath: "/tmp/traefik/logs/access.log"
#  format: "json"
#providers:
#  docker: {}
## Declaring the user list
#http:
#  middlewares:
#    test-auth:
#      basicAuth:
#        users:
#          - "test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"
#          - "test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0"
#    # Define an authentication mechanism
#    test-user:
#      basicAuth:
#        users:
#          - test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/
entryPoints:
  web:
    # Listen on port 8081 for incoming requests
    address: :8081

providers:
  # Enable the file provider to define routers / middlewares / services in a file
  file:
    filename: dynamic_conf1.yml
