# http routing section
http:
  routers:
    # Define a connection between requests and services
    to-whoami:
      rule: "Host(`domain`) && PathPrefix(`/whoami/`)"
       # If the rule matches, applies the middleware
      middlewares:
      - test-user
      # If the rule matches, forward to the whoami service (declared below)
      service: whoami

  middlewares:
    # Define an authentication mechanism
#    test-user:
#      basicAuth:
#        users:
#        - test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/
#        - user:$apr1$aGZmqKUc$s5ok/AkZV8lZvVFfgDh3F0
#        headerField: "X-WebAuth-User"
#        removeHeader: true
    test-user:
      forwardAuth:
        address: "https://authserver.com/auth"
  services:
    # Define how to reach an existing service on our infrastructure
    whoami:
      loadBalancer:
        servers:
        - url: http://localhost
#        - url: http://private/whoami-service
